name: gooey_edge
description:

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.4+2
  equatable: ^1.1.0
  get_it: ^1.0.3+1
  shared_preferences: ^0.5.1+2
  flushbar: 1.9.1
  scoped_model: ^1.0.1
  intl: any
  flutter_webview_plugin: ^0.3.10+1
  url_launcher: ^5.4.7
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  firebase_storage: ^3.1.5
  firebase_messaging: ^6.0.13
  image_picker: ^0.6.7+4

  shared:
      path: ../_shared/

  cupertino_icons: ^0.1.2

flutter:

  uses-material-design: true

  assets:
   - images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/Open-Sans/OpenSans-Regular.ttf
        - asset: fonts/Open-Sans/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/Open-Sans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/Open-Sans/OpenSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Open-Sans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/Open-Sans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Open-Sans/OpenSans-Semibold.ttf
          weight: 600
        - asset: fonts/Open-Sans/OpenSans-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Open-Sans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/Open-Sans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: DMSerifDisplay
      fonts:
        - asset: fonts/DM-Serif-Display/DMSerifDisplay-Regular.ttf
        - asset: fonts/DM-Serif-Display/DMSerifDisplay-Italic.ttf
          style: italic